title: Auditing with EF Core in .net 5
description: How to enable database table auditing 
author: Nicola Biada

# theme: jekyll-theme-cayman
remote_theme: carlosperate/jekyll-theme-rtd

collapse_navigation: true
include_homepage_in_sidebar: false

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://biada.it"
  
social-network-links:
  email: "nicola@biada.it"
  facebook: nicola.biada
  github: nbiada
  twitter: BiadaNicola
  linkedin: nicolabiada

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# Output options (more information on Jekyll's site)
# timezone: "Europe/Rome"
# markdown: kramdown
# highlighter: rouge
# permalink: /:year-:month-:day-:title/
# paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

theme: jekyll-theme-cayman
